# Generated by Django 5.0.6 on 2026-09-16 11:01

import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('score_or_grade', models.CharField(blank=True, max_length=50)),
                ('document_proof', models.FileField(blank=True, null=True, upload_to='profiles/credentials/%Y/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Credential',
                'verbose_name_plural': 'Academic Credentials',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('designation', models.CharField(choices=[('PROFESSOR', 'Full Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('SENIOR_LECTURER', 'Senior Lecturer'), ('LECTURER', 'Lecturer'), ('ADJUNCT_FACULTY', 'Adjunct Faculty'), ('VISITING_SCHOLAR', 'Visiting Scholar'), ('TEACHING_FELLOW', 'Teaching Fellow')], default='ASSISTANT_PROFESSOR', max_length=40)),
                ('office_room', models.CharField(blank=True, max_length=100)),
                ('office_hours', models.CharField(blank=True, help_text='e.g. Mon & Wed 2:00 PM - 4:00 PM', max_length=200)),
                ('research_interests', models.TextField(blank=True)),
                ('google_scholar_url', models.URLField(blank=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor / Faculty Profile',
                'verbose_name_plural': 'Instructor / Faculty Profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[apps.core.validators.validate_gpa_score])),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=25, validators=[apps.core.validators.validate_phone_number])),
                ('current_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.semester')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='courses.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Academic Profile',
                'verbose_name_plural': 'Student Academic Profiles',
            },
        ),
        migrations.CreateModel(
            name='SkillRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Record',
                'verbose_name_plural': 'Skill Records',
                'unique_together': {('user', 'skill_name')},
            },
        ),
    ]
