# Generated by Django 5.0.6 on 2026-09-16 11:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Cycle Title (e.g. Fall 2026 Admissions)')),
                ('start_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('max_seats', models.PositiveIntegerField(default=120)),
                ('is_open', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_cycles', to='courses.program')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_cycles', to='institutions.academicsession')),
            ],
            options={
                'verbose_name': 'Admission Cycle',
                'verbose_name_plural': 'Admission Cycles',
                'ordering': ['-application_deadline'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('statement_of_purpose', models.TextField(verbose_name='Statement of Purpose (SOP)')),
                ('prior_institution', models.CharField(max_length=255, verbose_name='Prior School / University')),
                ('prior_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Application'), ('SUBMITTED', 'Submitted & Pending Review'), ('UNDER_REVIEW', 'Under Committee Review'), ('SHORTLISTED', 'Shortlisted for Interview'), ('ACCEPTED', 'Accepted / Offer Issued'), ('REJECTED', 'Application Rejected'), ('WAITLISTED', 'Waitlisted'), ('ENROLLED', 'Formally Enrolled')], default='SUBMITTED', max_length=30)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='enrollments.admissioncycle')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Batch Title (e.g. 2026-Cohort-A)')),
                ('section', models.CharField(default='A', max_length=10, verbose_name='Section')),
                ('max_capacity', models.PositiveIntegerField(default=60)),
                ('current_strength', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_batches', to=settings.AUTH_USER_MODEL, verbose_name='Faculty Advisor / Mentor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.program')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='institutions.academicsession')),
            ],
            options={
                'verbose_name': 'Cohort / Batch',
                'verbose_name_plural': 'Cohorts / Batches',
                'ordering': ['name'],
                'unique_together': {('program', 'session', 'name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.course')),
                ('last_accessed_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Progress Tracker',
                'verbose_name_plural': 'Course Progress Trackers',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Progress Record',
                'verbose_name_plural': 'Lesson Progress Records',
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('ACTIVE', 'Actively Enrolled'), ('COMPLETED', 'Successfully Completed'), ('DROPPED', 'Dropped Course'), ('WITHDRAWN', 'Officially Withdrawn'), ('SUSPENDED', 'Academic Suspension')], default='ACTIVE', max_length=30)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('letter_grade', models.CharField(blank=True, max_length=5)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollments', to='enrollments.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='institutions.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Course Enrollment',
                'verbose_name_plural': 'Student Course Enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
