# Generated by Django 5.0.6 on 2026-09-16 11:01

import apps.core.validators
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Administrator'), ('INSTITUTION_ADMIN', 'Institution Administrator'), ('DEAN', 'Dean / Faculty Head'), ('DEPARTMENT_HEAD', 'Head of Department'), ('INSTRUCTOR', 'Faculty / Instructor'), ('TEACHING_ASSISTANT', 'Teaching Assistant'), ('STUDENT', 'Student / Learner'), ('PARENT', 'Parent / Guardian'), ('MENTOR', 'Career Mentor / Advisor'), ('CORPORATE_PARTNER', 'Corporate Training Partner'), ('ALUMNI', 'Alumni Member'), ('AUDITOR', 'Academic Auditor')], db_index=True, default='STUDENT', max_length=30, verbose_name='System Role')),
                ('phone_number', models.CharField(blank=True, max_length=25, validators=[apps.core.validators.validate_phone_number], verbose_name='Phone Number')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/%Y/%m/', verbose_name='Profile Picture')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('PREFER_NOT_TO_SAY', 'Prefer Not to Say'), ('OTHER', 'Other')], default='PREFER_NOT_TO_SAY', max_length=25, verbose_name='Gender')),
                ('bio', models.TextField(blank=True, verbose_name='Biography / About')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Identity Verified')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Two-Factor Authentication Enabled')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Recorded Activity')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_code', models.CharField(db_index=True, max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication Token',
                'verbose_name_plural': 'Two-Factor Authentication Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSessionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Session Log',
                'verbose_name_plural': 'User Session Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
