"""
Global Higher Education Institutional Registry
Standardized records of world-class universities and colleges.
"""

GLOBAL_UNIVERSITIES = [
    {
        "name": "Harvard University",
        "code": "HARVARD",
        "city": "Cambridge",
        "country": "United States",
        "established_year": 1636,
        "motto": "Veritas (Truth)",
        "contact_email": "info@harvard.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://harvard.edu",
    },
    {
        "name": "Stanford University",
        "code": "STANFORD",
        "city": "Stanford",
        "country": "United States",
        "established_year": 1885,
        "motto": "Die Luft der Freiheit weht",
        "contact_email": "admissions@stanford.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://stanford.edu",
    },
    {
        "name": "Massachusetts Institute of Technology",
        "code": "MIT",
        "city": "Cambridge",
        "country": "United States",
        "established_year": 1861,
        "motto": "Mens et Manus",
        "contact_email": "admissions@mit.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://mit.edu",
    },
    {
        "name": "University of Oxford",
        "code": "OXFORD",
        "city": "Oxford",
        "country": "United Kingdom",
        "established_year": 1096,
        "motto": "Dominus Illuminatio Mea",
        "contact_email": "enquiries@ox.ac.uk",
        "accreditation_grade": "Grade A++",
        "website": "https://ox.ac.uk",
    },
    {
        "name": "University of Cambridge",
        "code": "CAMBRIDGE",
        "city": "Cambridge",
        "country": "United Kingdom",
        "established_year": 1209,
        "motto": "Hinc lucem et pocula sacra",
        "contact_email": "admissions@cam.ac.uk",
        "accreditation_grade": "Grade A++",
        "website": "https://cam.ac.uk",
    },
    {
        "name": "California Institute of Technology",
        "code": "CALTECH",
        "city": "Pasadena",
        "country": "United States",
        "established_year": 1891,
        "motto": "The truth shall make you free",
        "contact_email": "admissions@caltech.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://caltech.edu",
    },
    {
        "name": "ETH Zurich",
        "code": "ETH-ZURICH",
        "city": "Zurich",
        "country": "Switzerland",
        "established_year": 1855,
        "motto": "Where the future begins",
        "contact_email": "info@ethz.ch",
        "accreditation_grade": "Grade A++",
        "website": "https://ethz.ch",
    },
    {
        "name": "Imperial College London",
        "code": "IMPERIAL",
        "city": "London",
        "country": "United Kingdom",
        "established_year": 1907,
        "motto": "Scientia imperii decus et tutamen",
        "contact_email": "admissions@imperial.ac.uk",
        "accreditation_grade": "Grade A++",
        "website": "https://imperial.ac.uk",
    },
    {
        "name": "University College London",
        "code": "UCL",
        "city": "London",
        "country": "United Kingdom",
        "established_year": 1826,
        "motto": "Cuncti adsint meritaeque expectent praemia palmae",
        "contact_email": "study@ucl.ac.uk",
        "accreditation_grade": "Grade A+",
        "website": "https://ucl.ac.uk",
    },
    {
        "name": "National University of Singapore",
        "code": "NUS",
        "city": "Singapore",
        "country": "Singapore",
        "established_year": 1905,
        "motto": "Towards a Global Knowledge Enterprise",
        "contact_email": "admissions@nus.edu.sg",
        "accreditation_grade": "Grade A++",
        "website": "https://nus.edu.sg",
    },
    {
        "name": "Nanyang Technological University",
        "code": "NTU",
        "city": "Singapore",
        "country": "Singapore",
        "established_year": 1991,
        "motto": "A Great Global University",
        "contact_email": "admissions@ntu.edu.sg",
        "accreditation_grade": "Grade A+",
        "website": "https://ntu.edu.sg",
    },
    {
        "name": "Tsinghua University",
        "code": "TSINGHUA",
        "city": "Beijing",
        "country": "China",
        "established_year": 1911,
        "motto": "Self-Discipline and Social Commitment",
        "contact_email": "admission@tsinghua.edu.cn",
        "accreditation_grade": "Grade A++",
        "website": "https://tsinghua.edu.cn",
    },
    {
        "name": "Peking University",
        "code": "PKU",
        "city": "Beijing",
        "country": "China",
        "established_year": 1898,
        "motto": "Patriotism, Progress, Democracy, and Science",
        "contact_email": "admission@pku.edu.cn",
        "accreditation_grade": "Grade A++",
        "website": "https://pku.edu.cn",
    },
    {
        "name": "University of Tokyo",
        "code": "UTOKYO",
        "city": "Tokyo",
        "country": "Japan",
        "established_year": 1877,
        "motto": "Discover Excellence",
        "contact_email": "contact@u-tokyo.ac.jp",
        "accreditation_grade": "Grade A++",
        "website": "https://u-tokyo.ac.jp",
    },
    {
        "name": "Kyoto University",
        "code": "KYOTO",
        "city": "Kyoto",
        "country": "Japan",
        "established_year": 1897,
        "motto": "Freedom of Academic Culture",
        "contact_email": "info@kyoto-u.ac.jp",
        "accreditation_grade": "Grade A+",
        "website": "https://kyoto-u.ac.jp",
    },
    {
        "name": "University of Toronto",
        "code": "UTORONTO",
        "city": "Toronto",
        "country": "Canada",
        "established_year": 1827,
        "motto": "Velut arbor aevo (As a tree through the ages)",
        "contact_email": "admissions@utoronto.ca",
        "accreditation_grade": "Grade A++",
        "website": "https://utoronto.ca",
    },
    {
        "name": "McGill University",
        "code": "MCGILL",
        "city": "Montreal",
        "country": "Canada",
        "established_year": 1821,
        "motto": "Grandescunt Aucta Labore",
        "contact_email": "admissions@mcgill.ca",
        "accreditation_grade": "Grade A+",
        "website": "https://mcgill.ca",
    },
    {
        "name": "University of Melbourne",
        "code": "UNIMELB",
        "city": "Melbourne",
        "country": "Australia",
        "established_year": 1853,
        "motto": "Postera crescam laude",
        "contact_email": "study@unimelb.edu.au",
        "accreditation_grade": "Grade A++",
        "website": "https://unimelb.edu.au",
    },
    {
        "name": "Australian National University",
        "code": "ANU",
        "city": "Canberra",
        "country": "Australia",
        "established_year": 1946,
        "motto": "Naturam primum cognoscere rerum",
        "contact_email": "admissions@anu.edu.au",
        "accreditation_grade": "Grade A+",
        "website": "https://anu.edu.au",
    },
    {
        "name": "University of Sydney",
        "code": "USYD",
        "city": "Sydney",
        "country": "Australia",
        "established_year": 1850,
        "motto": "Sidere mens eadem mutato",
        "contact_email": "admissions@sydney.edu.au",
        "accreditation_grade": "Grade A+",
        "website": "https://sydney.edu.au",
    },
    {
        "name": "Princeton University",
        "code": "PRINCETON",
        "city": "Princeton",
        "country": "United States",
        "established_year": 1746,
        "motto": "Dei Sub Numine Viget",
        "contact_email": "uaoffice@princeton.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://princeton.edu",
    },
    {
        "name": "Yale University",
        "code": "YALE",
        "city": "New Haven",
        "country": "United States",
        "established_year": 1701,
        "motto": "Lux et Veritas (Light and Truth)",
        "contact_email": "admissions@yale.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://yale.edu",
    },
    {
        "name": "Columbia University",
        "code": "COLUMBIA",
        "city": "New York",
        "country": "United States",
        "established_year": 1754,
        "motto": "In lumine Tuo videbimus lumen",
        "contact_email": "ugrad-ask@columbia.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://columbia.edu",
    },
    {
        "name": "University of Chicago",
        "code": "UCHICAGO",
        "city": "Chicago",
        "country": "United States",
        "established_year": 1890,
        "motto": "Crescat scientia; vita excolatur",
        "contact_email": "collegeadmissions@uchicago.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://uchicago.edu",
    },
    {
        "name": "University of Pennsylvania",
        "code": "UPENN",
        "city": "Philadelphia",
        "country": "United States",
        "established_year": 1740,
        "motto": "Leges sine moribus vanae",
        "contact_email": "admissions@upenn.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://upenn.edu",
    },
    {
        "name": "Cornell University",
        "code": "CORNELL",
        "city": "Ithaca",
        "country": "United States",
        "established_year": 1865,
        "motto": "I would found an institution where any person can find instruction in any study",
        "contact_email": "admissions@cornell.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://cornell.edu",
    },
    {
        "name": "Johns Hopkins University",
        "code": "JHU",
        "city": "Baltimore",
        "country": "United States",
        "established_year": 1876,
        "motto": "Veritas vos liberabit",
        "contact_email": "gotojhu@jhu.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://jhu.edu",
    },
    {
        "name": "University of California, Berkeley",
        "code": "UCB",
        "city": "Berkeley",
        "country": "United States",
        "established_year": 1868,
        "motto": "Fiat Lux (Let there be light)",
        "contact_email": "admissions@berkeley.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://berkeley.edu",
    },
    {
        "name": "University of California, Los Angeles",
        "code": "UCLA",
        "city": "Los Angeles",
        "country": "United States",
        "established_year": 1919,
        "motto": "Fiat Lux",
        "contact_email": "admissions@ucla.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://ucla.edu",
    },
    {
        "name": "University of Michigan",
        "code": "UMICH",
        "city": "Ann Arbor",
        "country": "United States",
        "established_year": 1817,
        "motto": "Artes, Scientia, Veritas",
        "contact_email": "admissions@umich.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://umich.edu",
    },
    {
        "name": "Carnegie Mellon University",
        "code": "CMU",
        "city": "Pittsburgh",
        "country": "United States",
        "established_year": 1900,
        "motto": "My heart is in the work",
        "contact_email": "admission@cmu.edu",
        "accreditation_grade": "Grade A++",
        "website": "https://cmu.edu",
    },
    {
        "name": "Technical University of Munich",
        "code": "TUM",
        "city": "Munich",
        "country": "Germany",
        "established_year": 1868,
        "motto": "The Entrepreneurial University",
        "contact_email": "studium@tum.de",
        "accreditation_grade": "Grade A++",
        "website": "https://tum.de",
    },
    {
        "name": "Heidelberg University",
        "code": "HEIDELBERG",
        "city": "Heidelberg",
        "country": "Germany",
        "established_year": 1386,
        "motto": "Semper Apertus",
        "contact_email": "studium@uni-heidelberg.de",
        "accreditation_grade": "Grade A+",
        "website": "https://uni-heidelberg.de",
    },
    {
        "name": "Paris Sciences et Lettres",
        "code": "PSL",
        "city": "Paris",
        "country": "France",
        "established_year": 2010,
        "motto": "Sapere Aude",
        "contact_email": "admissions@psl.eu",
        "accreditation_grade": "Grade A++",
        "website": "https://psl.eu",
    },
    {
        "name": "Institut Polytechnique de Paris",
        "code": "IP-PARIS",
        "city": "Palaiseau",
        "country": "France",
        "established_year": 2019,
        "motto": "Excellence in Science and Technology",
        "contact_email": "contact@ip-paris.fr",
        "accreditation_grade": "Grade A+",
        "website": "https://ip-paris.fr",
    },
    {
        "name": "Karolinska Institute",
        "code": "KAROLINSKA",
        "city": "Stockholm",
        "country": "Sweden",
        "established_year": 1810,
        "motto": "Att genom forskning och utbildning förbättra människors hälsa",
        "contact_email": "info@ki.se",
        "accreditation_grade": "Grade A++",
        "website": "https://ki.se",
    },
    {
        "name": "Sorbonne University",
        "code": "SORBONNE",
        "city": "Paris",
        "country": "France",
        "established_year": 1257,
        "motto": "Créateurs de futurs depuis 1257",
        "contact_email": "admissions@sorbonne-universite.fr",
        "accreditation_grade": "Grade A+",
        "website": "https://sorbonne-universite.fr",
    },
    {
        "name": "King's College London",
        "code": "KCL",
        "city": "London",
        "country": "United Kingdom",
        "established_year": 1829,
        "motto": "Sancte et Sapienter (With holiness and wisdom)",
        "contact_email": "admissions@kcl.ac.uk",
        "accreditation_grade": "Grade A+",
        "website": "https://kcl.ac.uk",
    },
    {
        "name": "University of Edinburgh",
        "code": "EDINBURGH",
        "city": "Edinburgh",
        "country": "United Kingdom",
        "established_year": 1583,
        "motto": "Nec tamen consumebatur",
        "contact_email": "futurestudents@ed.ac.uk",
        "accreditation_grade": "Grade A++",
        "website": "https://ed.ac.uk",
    },
    {
        "name": "University of Manchester",
        "code": "MANCHESTER",
        "city": "Manchester",
        "country": "United Kingdom",
        "established_year": 1824,
        "motto": "Cognitio, sapientia, humanitas",
        "contact_email": "study@manchester.ac.uk",
        "accreditation_grade": "Grade A+",
        "website": "https://manchester.ac.uk",
    },
    {
        "name": "Seoul National University",
        "code": "SNU",
        "city": "Seoul",
        "country": "South Korea",
        "established_year": 1946,
        "motto": "Veritas lux mea",
        "contact_email": "snuadmit@snu.ac.kr",
        "accreditation_grade": "Grade A++",
        "website": "https://snu.ac.kr",
    },
    {
        "name": "Korea Advanced Institute of Science & Technology",
        "code": "KAIST",
        "city": "Daejeon",
        "country": "South Korea",
        "established_year": 1971,
        "motto": "Creation, Challenge, Caring",
        "contact_email": "admission@kaist.ac.kr",
        "accreditation_grade": "Grade A+",
        "website": "https://kaist.ac.kr",
    },
    {
        "name": "University of Hong Kong",
        "code": "HKU",
        "city": "Hong Kong",
        "country": "Hong Kong",
        "established_year": 1911,
        "motto": "Sapientia et Virtus",
        "contact_email": "admissions@hku.hk",
        "accreditation_grade": "Grade A++",
        "website": "https://hku.hk",
    },
    {
        "name": "Hong Kong University of Science and Technology",
        "code": "HKUST",
        "city": "Hong Kong",
        "country": "Hong Kong",
        "established_year": 1991,
        "motto": "Hands on the present, eyes on the future",
        "contact_email": "ugadmit@ust.hk",
        "accreditation_grade": "Grade A+",
        "website": "https://ust.hk",
    },
    {
        "name": "Indian Institute of Technology Bombay",
        "code": "IIT-BOMBAY",
        "city": "Mumbai",
        "country": "India",
        "established_year": 1958,
        "motto": "Gyanam Paramam Dhyeyam",
        "contact_email": "jeeoffice@iitb.ac.in",
        "accreditation_grade": "Grade A++",
        "website": "https://iitb.ac.in",
    },
    {
        "name": "Indian Institute of Technology Delhi",
        "code": "IIT-DELHI",
        "city": "New Delhi",
        "country": "India",
        "established_year": 1961,
        "motto": "Excellence in Technology and Research",
        "contact_email": "admissions@iitd.ac.in",
        "accreditation_grade": "Grade A++",
        "website": "https://iitd.ac.in",
    },
    {
        "name": "Indian Institute of Science",
        "code": "IISC",
        "city": "Bengaluru",
        "country": "India",
        "established_year": 1909,
        "motto": "Discover and Innovate",
        "contact_email": "admissions@iisc.ac.in",
        "accreditation_grade": "Grade A++",
        "website": "https://iisc.ac.in",
    },
    {
        "name": "University of Auckland",
        "code": "AUCKLAND",
        "city": "Auckland",
        "country": "New Zealand",
        "established_year": 1883,
        "motto": "Ingenio et labore",
        "contact_email": "studentinfo@auckland.ac.nz",
        "accreditation_grade": "Grade A+",
        "website": "https://auckland.ac.nz",
    },
    {
        "name": "Trinity College Dublin",
        "code": "TCD",
        "city": "Dublin",
        "country": "Ireland",
        "established_year": 1592,
        "motto": "Perpetuis futuris temporibus duraturam",
        "contact_email": "academic.registry@tcd.ie",
        "accreditation_grade": "Grade A+",
        "website": "https://tcd.ie",
    },
    {
        "name": "KU Leuven",
        "code": "KULEUVEN",
        "city": "Leuven",
        "country": "Belgium",
        "established_year": 1425,
        "motto": "Sedes Sapientiae",
        "contact_email": "info@kuleuven.be",
        "accreditation_grade": "Grade A++",
        "website": "https://kuleuven.be",
    },
]

UNIVERSITIES_BY_CODE = {u["code"]: u for u in GLOBAL_UNIVERSITIES}
