# Generated by Django 5.0.6 on 2026-09-16 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Configuration Key')),
                ('value', models.TextField(verbose_name='Configuration Value')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Setting Description')),
                ('is_public', models.BooleanField(default=False, verbose_name='Publicly Accessible in Frontend')),
            ],
            options={
                'verbose_name': 'System Configuration Setting',
                'verbose_name_plural': 'System Configuration Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Notification Title')),
                ('message', models.TextField(verbose_name='Notification Message Content')),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical / Urgent')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Destination URL')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Notification Recipient')),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created Record'), ('UPDATE', 'Updated Record'), ('DELETE', 'Deleted Record'), ('SOFT_DELETE', 'Soft-Deleted Record'), ('RESTORE', 'Restored Record'), ('LOGIN_SUCCESS', 'Successful Authentication'), ('LOGIN_FAILED', 'Failed Authentication Attempt'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset Requested'), ('PERMISSION_CHANGE', 'Role / Permissions Altered'), ('DATA_EXPORT', 'Sensitive Data Exported'), ('IMPERSONATION_START', 'Admin Impersonation Started'), ('IMPERSONATION_END', 'Admin Impersonation Ended')], db_index=True, max_length=40, verbose_name='Action')),
                ('entity_name', models.CharField(db_index=True, max_length=120, verbose_name='Entity Affected')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Entity Primary Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Browser User Agent')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP Method')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Request URL Path')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Log Metadata Details')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP Status Code')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Acting User')),
            ],
            options={
                'verbose_name': 'Audit Activity Log',
                'verbose_name_plural': 'Audit Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_activi_action_4055cf_idx'), models.Index(fields=['user', 'created_at'], name='core_activi_user_id_599332_idx'), models.Index(fields=['entity_name', 'entity_id'], name='core_activi_entity__8f4e55_idx')],
            },
        ),
    ]
