# Generated by Django 5.0.6 on 2026-09-16 11:01

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug URL')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug URL')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Course Code (e.g. CS-101)')),
                ('credit_hours', models.DecimalField(decimal_places=1, default=3.0, max_digits=4, validators=[apps.core.validators.validate_credit_hours])),
                ('lecture_hours', models.PositiveSmallIntegerField(default=3, verbose_name='Weekly Lecture Hours')),
                ('lab_hours', models.PositiveSmallIntegerField(default=0, verbose_name='Weekly Practical/Lab Hours')),
                ('academic_level', models.CharField(choices=[('PRIMARY', 'Primary Education'), ('SECONDARY', 'Secondary Education'), ('HIGHER_SECONDARY', 'Higher Secondary'), ('UNDERGRADUATE', 'Undergraduate Degree (Bachelor)'), ('POSTGRADUATE', 'Postgraduate Degree (Master)'), ('DOCTORATE', 'Doctorate (Ph.D.)'), ('DIPLOMA', 'Post-Secondary Diploma'), ('CERTIFICATE', 'Professional Certification'), ('EXECUTIVE_EDUCATION', 'Executive Education')], default='UNDERGRADUATE', max_length=30)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/%Y/%m/')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='Short Summary')),
                ('description', models.TextField(verbose_name='Detailed Course Syllabus & Overview')),
                ('syllabus_document', models.FileField(blank=True, null=True, upload_to='courses/syllabi/%Y/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived'), ('SUSPENDED', 'Suspended'), ('DELETED', 'Soft Deleted')], default='ACTIVE', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutions.academicdepartment')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_courses', to='courses.course')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Module Title (e.g. Unit 1: Graph Theory)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Module Order')),
                ('summary', models.TextField(blank=True, verbose_name='Module Summary')),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Module / Unit',
                'verbose_name_plural': 'Course Modules / Units',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Lesson Title')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Streaming Video Lesson'), ('ARTICLE', 'Interactive Reading & Markdown'), ('SCORM', 'SCORM / e-Learning Package'), ('CODE_SANDBOX', 'Coding Exercise'), ('DOWNLOADABLE', 'Downloadable Lecture Notes'), ('QUIZ', 'Module Checkpoint Quiz')], default='ARTICLE', max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Allow Free Preview')),
                ('body_text', models.TextField(blank=True, verbose_name='Lesson Content / Article Text')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube/Vimeo/HLS)')),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='courses/lessons/resources/%Y/%m/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug URL')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Program Name (e.g. B.Tech Computer Science)')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Program Code (e.g. BSCS)')),
                ('academic_level', models.CharField(choices=[('PRIMARY', 'Primary Education'), ('SECONDARY', 'Secondary Education'), ('HIGHER_SECONDARY', 'Higher Secondary'), ('UNDERGRADUATE', 'Undergraduate Degree (Bachelor)'), ('POSTGRADUATE', 'Postgraduate Degree (Master)'), ('DOCTORATE', 'Doctorate (Ph.D.)'), ('DIPLOMA', 'Post-Secondary Diploma'), ('CERTIFICATE', 'Professional Certification'), ('EXECUTIVE_EDUCATION', 'Executive Education')], default='UNDERGRADUATE', max_length=30)),
                ('total_credits_required', models.PositiveIntegerField(default=120, verbose_name='Total Credits Required for Graduation')),
                ('duration_semesters', models.PositiveSmallIntegerField(default=8, verbose_name='Standard Duration (Semesters)')),
                ('description', models.TextField(blank=True, verbose_name='Program Overview')),
                ('learning_outcomes', models.TextField(blank=True, verbose_name='Program Educational Objectives')),
                ('career_pathways', models.TextField(blank=True, verbose_name='Career Opportunities')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutions.academicdepartment')),
            ],
            options={
                'verbose_name': 'Academic Program / Degree',
                'verbose_name_plural': 'Academic Programs / Degrees',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='curriculum_courses', to='courses.program'),
        ),
        migrations.CreateModel(
            name='CourseInstructorAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_lead', models.BooleanField(default=False, verbose_name='Lead Instructor / Primary Coordinator')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_allocations', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_courses', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='institutions.semester')),
            ],
            options={
                'verbose_name': 'Course Faculty Allocation',
                'verbose_name_plural': 'Course Faculty Allocations',
                'unique_together': {('course', 'instructor', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('headline', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'student')},
            },
        ),
    ]
