# Generated by Django 5.0.6 on 2026-09-17 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChallengeSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('language', models.CharField(choices=[('PYTHON', 'Python 3.11'), ('JAVASCRIPT', 'JavaScript (Node.js)'), ('SQL', 'PostgreSQL / SQLite SQL'), ('CPP', 'C++ 20'), ('JAVA', 'Java 17 OpenJDK')], default='PYTHON', max_length=30)),
                ('starter_code', models.TextField(blank=True)),
                ('solution_code', models.TextField()),
                ('time_limit_ms', models.PositiveIntegerField(default=2000)),
                ('memory_limit_mb', models.PositiveIntegerField(default=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('assessment_type', models.CharField(choices=[('QUIZ', 'Module Quiz / Knowledge Check'), ('MIDTERM', 'Midterm Examination'), ('FINAL_EXAM', 'Comprehensive Final Examination'), ('PRACTICE_TEST', 'Diagnostic Practice Assessment'), ('LAB_EXAM', 'Laboratory Practical Exam')], default='QUIZ', max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_points', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('instructions_html', models.TextField(blank=True)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('allow_review', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('is_proctored', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.campus', verbose_name='Campus Location')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.academicdepartment', verbose_name='Academic Department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='institutions.institution', verbose_name='Institution / Organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_total_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.campus', verbose_name='Campus Location')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='courses.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.academicdepartment', verbose_name='Academic Department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='institutions.institution', verbose_name='Institution / Organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('section_points', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.assessment')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CodeTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('points', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('code_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assessments.codechallengespec')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('title', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('MCQ_SINGLE', 'Multiple Choice (Single Answer)'), ('MCQ_MULTIPLE', 'Multiple Choice (Multiple Answers)'), ('TRUE_FALSE', 'True / False'), ('SHORT_ANSWER', 'Short Answer'), ('ESSAY', 'Essay / Long Response'), ('FILL_BLANK', 'Fill in the Blanks'), ('MATCHING', 'Matching Pairs'), ('NUMERICAL', 'Numerical Calculation'), ('CODE_CHALLENGE', 'Coding Challenge / Sandbox')], default='MCQ_SINGLE', max_length=30)),
                ('prompt_html', models.TextField()),
                ('explanation_html', models.TextField(blank=True)),
                ('default_points', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('negative_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy (Introductory)'), ('MEDIUM', 'Medium (Standard)'), ('HARD', 'Hard (Advanced)'), ('EXPERT', 'Expert (Mastery / Research)')], default='MEDIUM', max_length=20)),
                ('blooms_level', models.CharField(choices=[('REMEMBERING', 'Remembering'), ('UNDERSTANDING', 'Understanding'), ('APPLYING', 'Applying'), ('ANALYZING', 'Analyzing'), ('EVALUATING', 'Evaluating'), ('CREATING', 'Creating')], default='APPLYING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.campus', verbose_name='Campus Location')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.academicdepartment', verbose_name='Academic Department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='institutions.institution', verbose_name='Institution / Organization')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentrubric')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='codechallengespec',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_spec', to='assessments.question'),
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.campus', verbose_name='Campus Location')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.academicdepartment', verbose_name='Academic Department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='institutions.institution', verbose_name='Institution / Organization')),
            ],
            options={
                'verbose_name_plural': 'Question Categories',
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='assessments.questioncategory'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('option_text', models.CharField(max_length=500)),
                ('option_html', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.question')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='assessments.questiontag'),
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('max_points', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessments.assessmentrubric')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('level_name', models.CharField(max_length=100)),
                ('point_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='assessments.rubriccriterion')),
            ],
            options={
                'ordering': ['-point_value'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('points_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='assessments.assessmentsection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_links', to='assessments.question')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('section', 'question')},
            },
        ),
    ]
