"""
Comprehensive National Center for Education Statistics (NCES) CIP Master Catalog
Standardized taxonomy of collegiate instructional degree programs.
"""

CIP_SERIES_CATALOG = [
    {
        "series_code": "01",
        "series_title": "Agricultural & Veterinary Sciences",
        "programs": [
            {
                "cip_code": "01.0000",
                "title": "Agriculture, General",
                "definition": "Instructional program that focuses on general principles and business of agriculture.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "01.0101",
                "title": "Agricultural Business and Management",
                "definition": "Focuses on the application of economics and business principles to the agriculture industry.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "01.0102",
                "title": "Agribusiness/Agricultural Business Operations",
                "definition": "Prepares individuals to manage agricultural businesses, cooperatives, and supply chains.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "01.0103",
                "title": "Agricultural Economics",
                "definition": "Focuses on the systematic analysis of economic issues in food, agriculture, and natural resources.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "01.0201",
                "title": "Agricultural Mechanization, General",
                "definition": "Focuses on the mechanics and technology used in agricultural systems and machinery.",
                "stem_designated": True,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "01.0301",
                "title": "Agricultural Production Operations",
                "definition": "Focuses on the application of scientific principles to crop and animal production.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "01.0901",
                "title": "Animal Sciences, General",
                "definition": "Focuses on the scientific principles of nutrition, breeding, and management of livestock.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "01.1001",
                "title": "Food Science",
                "definition": "Focuses on the biological, chemical, and physical nature of food and food processing principles.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "01.1101",
                "title": "Plant Sciences, General",
                "definition": "Focuses on the scientific study of plant biology, genetics, and physiology for agricultural applications.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "01.1201",
                "title": "Soil Science and Agronomy",
                "definition": "Focuses on the biological, chemical, and physical properties of soils and soil management.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
        ]
    },
    {
        "series_code": "03",
        "series_title": "Natural Resources & Conservation",
        "programs": [
            {
                "cip_code": "03.0101",
                "title": "Natural Resources/Conservation, General",
                "definition": "Instructional program focused on the conservation and management of natural systems.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "03.0103",
                "title": "Environmental Studies",
                "definition": "Focuses on the interaction of humans and natural environments using multi-disciplinary science.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "03.0104",
                "title": "Environmental Science",
                "definition": "Focuses on the physical, chemical, and biological analysis of environmental systems and remediation.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "03.0201",
                "title": "Natural Resources Management and Policy",
                "definition": "Focuses on policy development, administration, and regulatory enforcement of natural resources.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "03.0501",
                "title": "Forestry, General",
                "definition": "Focuses on the management, conservation, and harvesting of forest resources and timber.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "03.0601",
                "title": "Wildlife, Fish and Wildlands Science and Management",
                "definition": "Focuses on the preservation, management, and ecology of wildlife species and habitats.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
        ]
    },
    {
        "series_code": "04",
        "series_title": "Architecture & Environmental Design",
        "programs": [
            {
                "cip_code": "04.0201",
                "title": "Architecture",
                "definition": "Focuses on the art, science, and business of designing and building structures for human habitation.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "04.0301",
                "title": "City/Urban, Community and Regional Planning",
                "definition": "Focuses on the structural, social, and economic development of urban and regional spaces.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "04.0401",
                "title": "Environmental Design/Architecture",
                "definition": "Focuses on integrating physical architecture with natural ecological settings and microclimates.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "04.0501",
                "title": "Interior Architecture",
                "definition": "Focuses on the structural and functional design of interior spaces within architectural frameworks.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "04.0601",
                "title": "Landscape Architecture",
                "definition": "Focuses on the artistic and ecological design of outdoor public, commercial, and residential spaces.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "04.0901",
                "title": "Architectural Technology/Technician",
                "definition": "Prepares individuals to use CAD, BIM, and drafting tools to assist professional architects.",
                "stem_designated": True,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
        ]
    },
    {
        "series_code": "09",
        "series_title": "Communication, Journalism & Digital Media",
        "programs": [
            {
                "cip_code": "09.0101",
                "title": "Speech Communication and Rhetoric",
                "definition": "Focuses on interpersonal, group, and public discourse, rhetoric, and verbal communications.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "09.0102",
                "title": "Mass Communication/Media Studies",
                "definition": "Focuses on media production, analysis, regulatory policy, and audience reception in society.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "09.0401",
                "title": "Journalism",
                "definition": "Focuses on reporting, writing, editing, and publishing news stories across digital, print, and broadcast media.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "09.0701",
                "title": "Radio and Television",
                "definition": "Focuses on technical production, broadcasting, directing, and programming for audio/video media.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "09.0702",
                "title": "Digital Communication and Media/Multimedia",
                "definition": "Focuses on the creation and dissemination of digital content, interactive media, and streaming.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "09.0902",
                "title": "Public Relations/Image Management",
                "definition": "Focuses on strategic communications, brand advocacy, crisis communications, and reputation management.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
        ]
    },
    {
        "series_code": "11",
        "series_title": "Computer & Information Sciences",
        "programs": [
            {
                "cip_code": "11.0101",
                "title": "Computer and Information Sciences, General",
                "definition": "General program on computing theory, algorithms, and software development paradigms.",
                "stem_designated": True,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "11.0102",
                "title": "Artificial Intelligence",
                "definition": "Program on machine learning, natural language processing, neural architectures, and robotics.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "11.0103",
                "title": "Information Technology",
                "definition": "Program on network management, cloud architectures, enterprise storage, and tech support.",
                "stem_designated": True,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "11.0104",
                "title": "Informatics",
                "definition": "Program on domain-specific application of computing systems in health, sciences, and governance.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "11.0201",
                "title": "Computer Programming/Programmer, General",
                "definition": "Prepares individuals to write, debug, and maintain code in modern high-level languages.",
                "stem_designated": True,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'CERTIFICATE'],
            },
            {
                "cip_code": "11.0301",
                "title": "Data Processing and Data Processing Technology",
                "definition": "Focuses on automated batch data processing, transactional databases, and ETL systems.",
                "stem_designated": True,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "11.0401",
                "title": "Information Science/Studies",
                "definition": "Program on user experience, information behavior, digital libraries, and search systems.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "11.0501",
                "title": "Computer Systems Analysis/Analyst",
                "definition": "Prepares individuals to assess enterprise systems and design optimal computational architectures.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "11.0701",
                "title": "Computer Science",
                "definition": "Formal scientific study of computability, complexity theory, systems programming, and algorithms.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "11.0801",
                "title": "Web Page, Digital/Multimedia and Information Resources Design",
                "definition": "Program on front-end web development, responsive CSS, user interaction, and client-side scripting.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "11.0802",
                "title": "Data Modeling/Warehousing and Database Administration",
                "definition": "Program on database normalization, OLAP, star schemas, indexing, and high availability.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "11.0803",
                "title": "Computer Graphics",
                "definition": "Program on 3D geometry rendering, ray tracing, shader programming, and virtual reality.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "11.0804",
                "title": "Modeling, Virtual Environments and Simulation",
                "definition": "Program on physics simulation engines, computational modeling, and virtual simulations.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "11.0901",
                "title": "Computer Systems Networking and Telecommunications",
                "definition": "Program on network topology, routing protocols (BGP/OSPF), SDN, and wireless transmission.",
                "stem_designated": True,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "11.1001",
                "title": "Network and System Administration",
                "definition": "Program on Linux/Windows administration, automation (Ansible/Terraform), and directory services.",
                "stem_designated": True,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "11.1002",
                "title": "System, Networking, and LAN/WAN Management",
                "definition": "Focuses on enterprise campus network infrastructure, switching, VLANs, and firewalling.",
                "stem_designated": True,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "11.1003",
                "title": "Computer and Information Systems Security",
                "definition": "Program on penetration testing, cryptanalysis, zero trust, and security incident response.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "11.1004",
                "title": "Web/Multimedia Management and Webmaster",
                "definition": "Prepares individuals to administer web server clusters (Nginx/Apache), DNS, and TLS certificates.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "11.1005",
                "title": "Information Technology Project Management",
                "definition": "Focuses on agile, scrum, sprint planning, and budget management for software engineering teams.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "11.1006",
                "title": "Computer Support Specialist",
                "definition": "Prepares individuals to provide technical desktop and hardware troubleshooting support.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'CERTIFICATE'],
            },
        ]
    },
    {
        "series_code": "14",
        "series_title": "Engineering & Advanced Technology",
        "programs": [
            {
                "cip_code": "14.0101",
                "title": "Engineering, General",
                "definition": "Comprehensive foundational program in physics, math, and engineering problem-solving.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0201",
                "title": "Aerospace, Aeronautical and Astronautical Engineering",
                "definition": "Design of aircraft, orbital launch vehicles, propulsion systems, and orbital satellites.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0301",
                "title": "Agricultural Engineering",
                "definition": "Design of machinery, irrigation structures, and environmental remediation for farming.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0401",
                "title": "Architectural Engineering",
                "definition": "Design of structural, mechanical, electrical, and lighting systems inside buildings.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "14.0501",
                "title": "Bioengineering and Biomedical Engineering",
                "definition": "Application of engineering to medical prosthetics, physiological sensors, and drug delivery.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0601",
                "title": "Ceramic Sciences and Engineering",
                "definition": "Program on advanced ceramics, refractory materials, and high-temperature thermal barriers.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0701",
                "title": "Chemical Engineering",
                "definition": "Design of large-scale chemical reactors, mass transfer separation, and thermodynamics.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0801",
                "title": "Civil Engineering, General",
                "definition": "Design and analysis of public infrastructure, structural concrete, steel, and bridges.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0802",
                "title": "Geotechnical and Geoenvironmental Engineering",
                "definition": "Soil bearing mechanics, foundation piles, tunneling, and underground containment structures.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0803",
                "title": "Structural Engineering",
                "definition": "Non-linear structural analysis, earthquake ductile detailing, and finite element modeling.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0804",
                "title": "Transportation and Highway Engineering",
                "definition": "Geometric highway design, pavement materials, traffic stream theory, and mass transit.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0805",
                "title": "Water Resources Engineering",
                "definition": "Hydrology, flood risk modeling, stormwater containment, dams, and municipal aqueducts.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0901",
                "title": "Computer Engineering, General",
                "definition": "Design of microprocessors, digital logic, FPGA accelerators, and device firmware.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0902",
                "title": "Computer Hardware Engineering",
                "definition": "PCB circuit design, signal integrity analysis, high-speed buses, and silicon validation.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.0903",
                "title": "Computer Software Engineering",
                "definition": "Large-scale software system architecture, clean design patterns, and automated CI/CD.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.1001",
                "title": "Electrical and Electronics Engineering",
                "definition": "Circuit analysis, semiconductor physics, microelectronics, power grids, and telecommunications.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.1004",
                "title": "Telecommunications Engineering",
                "definition": "Cellular networks (5G/6G), RF antenna design, microwave waveguides, and optical fiber.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "14.1101",
                "title": "Engineering Mechanics",
                "definition": "Continuum mechanics, elasticity, plasticity, viscoelasticity, and computational fluid dynamics.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.1201",
                "title": "Engineering Physics",
                "definition": "Integration of quantum physics, lasers, superconductivity, and nanodevice fabrication.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.1301",
                "title": "Engineering Science",
                "definition": "Rigorous interdisciplinary program emphasizing mathematical foundations of natural phenomena.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.1401",
                "title": "Environmental/Environmental Health Engineering",
                "definition": "Water/wastewater treatment, air quality scrubbers, hazardous waste management, and GIS.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.1801",
                "title": "Materials Science and Engineering",
                "definition": "Crystalline structures, phase diagrams, metallurgy, polymers, and biomaterials.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.1901",
                "title": "Mechanical Engineering",
                "definition": "Thermodynamics, heat transfer, machine element design, vibrations, and mechatronics.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.2001",
                "title": "Metallurgical Engineering",
                "definition": "Extraction, smelting, refining, and alloy composition of ferrous and non-ferrous metals.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.2101",
                "title": "Mining and Mineral Engineering",
                "definition": "Subsurface rock mechanics, open-pit mine planning, ventilation, and mineral processing.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "14.2201",
                "title": "Naval Architecture and Marine Engineering",
                "definition": "Hydrodynamics of ship hulls, marine propulsion, offshore drilling platforms, and stability.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.2301",
                "title": "Nuclear Engineering",
                "definition": "Fission reactor physics, neutron transport equations, radiation shielding, and fusion energy.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.2401",
                "title": "Ocean Engineering",
                "definition": "Coastal sediment transport, wave mechanics, underwater acoustics, and ROV submarines.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.2501",
                "title": "Petroleum Engineering",
                "definition": "Reservoir simulation, directional drilling, hydraulic fracturing, and well production logging.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.2701",
                "title": "Systems Engineering",
                "definition": "Lifecycle engineering, requirements verification, risk quantification, and system integration.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.3501",
                "title": "Industrial Engineering",
                "definition": "Operations research, queuing models, lean manufacturing, ergonomics, and supply chain logistics.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "14.4201",
                "title": "Mechatronics, Robotics, and Automation Engineering",
                "definition": "Embedded controllers, robotic kinematics, feedback servo control, sensors, and actuators.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
        ]
    },
    {
        "series_code": "26",
        "series_title": "Biological & Biomedical Sciences",
        "programs": [
            {
                "cip_code": "26.0101",
                "title": "Biology/Biological Sciences, General",
                "definition": "Comprehensive study of cellular processes, genetics, ecology, and evolutionary biology.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.0202",
                "title": "Biochemistry",
                "definition": "Chemical processes within living organisms, enzymatic pathways, and protein folding.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.0204",
                "title": "Molecular Biology",
                "definition": "DNA replication, transcription, RNA processing, gene regulation, and recombinant cloning.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.0406",
                "title": "Cell/Cellular and Molecular Biology",
                "definition": "Organelle functions, signaling cascades, membrane transport, and mitotic cell division.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.0502",
                "title": "Microbiology, General",
                "definition": "Biology of bacteria, viruses, fungi, and protozoa in ecology, disease, and biotechnology.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.0801",
                "title": "Genetics, General",
                "definition": "Mendelian inheritance, population genetics, chromosomal anomalies, and gene therapy.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.0901",
                "title": "Physiology, General",
                "definition": "Functions and vital processes of tissues, organs, and integrated biological systems.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.1102",
                "title": "Biostatistics",
                "definition": "Statistical methodologies applied to clinical trials, epidemiological studies, and public health.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.1103",
                "title": "Bioinformatics",
                "definition": "Computational sequence alignment, genomics annotation, proteomics, and structural modeling.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.1201",
                "title": "Biotechnology",
                "definition": "Application of living organisms and bioprocesses to medicine, agriculture, and industry.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.1301",
                "title": "Ecology",
                "definition": "Interactions of organisms with physical environments, biogeochemical cycles, and biodiversity.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "26.1501",
                "title": "Neuroscience",
                "definition": "Neuroanatomy, synaptic transmission, cognitive neural circuits, and neurological disorders.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
        ]
    },
    {
        "series_code": "27",
        "series_title": "Mathematics & Statistics",
        "programs": [
            {
                "cip_code": "27.0101",
                "title": "Mathematics, General",
                "definition": "Symbolic logic, real analysis, abstract algebra, topology, and number theory.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "27.0301",
                "title": "Applied Mathematics, General",
                "definition": "Mathematical modeling of engineering, fluid, biological, and physical systems.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "27.0303",
                "title": "Computational Mathematics",
                "definition": "Numerical root finding, matrix decompositions, finite differences, and algorithm stability.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "27.0304",
                "title": "Computational and Applied Mathematics",
                "definition": "High-performance computing applied to differential equations and scientific simulations.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "27.0305",
                "title": "Financial Mathematics",
                "definition": "Stochastic calculus, Black-Scholes pricing, interest rate models, and risk management.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "27.0501",
                "title": "Statistics, General",
                "definition": "Probability theory, hypothesis testing, linear models, and multivariate analysis.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "27.0502",
                "title": "Mathematical Statistics and Probability",
                "definition": "Measure-theoretic probability, central limit theorems, and asymptotic inference.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "27.0503",
                "title": "Mathematics and Statistics",
                "definition": "Integrated curriculum combining pure mathematical theory with empirical statistical methods.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "27.0601",
                "title": "Applied Statistics, General",
                "definition": "Regression diagnostics, ANOVA, statistical quality control, and data visualization.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
        ]
    },
    {
        "series_code": "40",
        "series_title": "Physical Sciences",
        "programs": [
            {
                "cip_code": "40.0101",
                "title": "Physical Sciences",
                "definition": "Interdisciplinary study of non-living matter, thermodynamics, and physical dynamics.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0201",
                "title": "Astronomy",
                "definition": "Observational astrophysics, planetary dynamics, stellar evolution, and cosmic expansion.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0202",
                "title": "Astrophysics",
                "definition": "Relativistic plasma physics, nuclear fusion in stars, black holes, and dark matter.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0501",
                "title": "Chemistry, General",
                "definition": "Atomic theory, chemical bonding, stoichiometry, and kinetics of organic/inorganic compounds.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0502",
                "title": "Analytical Chemistry",
                "definition": "Chromatography, mass spectrometry, spectroscopy, and quantitative trace detection.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0504",
                "title": "Organic Chemistry",
                "definition": "Carbon synthesis, reaction mechanisms, stereochemistry, and spectroscopy NMR analysis.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0506",
                "title": "Physical Chemistry",
                "definition": "Thermodynamic equations of state, quantum chemistry, and molecular spectroscopy.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0601",
                "title": "Geology/Earth Science, General",
                "definition": "Plate tectonics, mineralogy, structural geology, stratigraphy, and petrology.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0801",
                "title": "Physics, General",
                "definition": "Classical mechanics, electromagnetism, special relativity, and quantum mechanics.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0802",
                "title": "Atomic/Molecular Physics",
                "definition": "Atomic electron configurations, laser spectroscopy, and quantum interactions.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0804",
                "title": "Elementary Particle Physics",
                "definition": "Standard Model, quarks, leptons, gauge bosons, and quantum field theory (QFT).",
                "stem_designated": True,
                "degree_levels": ['MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0806",
                "title": "Nuclear Physics",
                "definition": "Nuclear shell model, radioactive decay kinetics, fission cross-sections, and particle accelerators.",
                "stem_designated": True,
                "degree_levels": ['MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0807",
                "title": "Optics/Optical Sciences",
                "definition": "Geometric optics, diffraction, wave interference, fiber optics, and laser design.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "40.0810",
                "title": "Theoretical and Mathematical Physics",
                "definition": "Differential geometry, group representations, string theory, and quantum gravity.",
                "stem_designated": True,
                "degree_levels": ['MASTER', 'DOCTORATE'],
            },
        ]
    },
    {
        "series_code": "52",
        "series_title": "Business, Management, Marketing & Finance",
        "programs": [
            {
                "cip_code": "52.0101",
                "title": "Business/Commerce, General",
                "definition": "Overview of accounting, commercial law, marketing, management, and global economics.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.0201",
                "title": "Business Administration and Management, General",
                "definition": "Corporate planning, organizational strategy, executive leadership, and resource allocation.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "52.0203",
                "title": "Logistics, Materials, and Supply Chain Management",
                "definition": "Inventory control (EOQ), freight logistics, warehouse management, and global sourcing.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.0204",
                "title": "Operations Management and Supervision",
                "definition": "Process mapping, quality assurance (Six Sigma), production scheduling, and capacity planning.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.0205",
                "title": "Operations Research",
                "definition": "Linear programming, simplex method, queuing theory, and stochastic decision models.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "52.0301",
                "title": "Accounting",
                "definition": "GAAP/IFRS compliance, audit standards, tax accounting, and financial reporting systems.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.0302",
                "title": "Accounting Technology/Technician and Bookkeeping",
                "definition": "Practical financial record keeping, payroll processing, and accounting software tools.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'CERTIFICATE'],
            },
            {
                "cip_code": "52.0304",
                "title": "Accounting and Finance",
                "definition": "Integrated study of corporate capital allocation, ledger accounts, and investor relations.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.0601",
                "title": "Business/Managerial Economics",
                "definition": "Pricing strategies, market equilibrium, competitive dynamics, and econometric modeling.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "52.0801",
                "title": "Finance, General",
                "definition": "Capital budgeting (NPV/IRR), equity valuation, fixed income bonds, and corporate mergers.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "52.0803",
                "title": "Banking and Financial Support Services",
                "definition": "Commercial bank underwriting, credit risk scoring, liquidity ratios, and central bank rules.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "52.0804",
                "title": "Financial Planning and Services",
                "definition": "Wealth management, personal portfolio allocation, retirement vehicles, and estate planning.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "52.0807",
                "title": "Investments and Securities",
                "definition": "Security analysis, stock market microstructure, hedge fund strategies, and derivatives trading.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.0808",
                "title": "Public Finance",
                "definition": "Municipal bond financing, public taxation policy, state budgeting, and debt issuance.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.1101",
                "title": "International Business/Trade/Commerce",
                "definition": "Cross-border trade agreements (WTO), foreign exchange hedging, and multinational management.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.1201",
                "title": "Management Information Systems, General",
                "definition": "Enterprise ERP systems, database querying, business intelligence, and IT infrastructure.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "52.1301",
                "title": "Management Science",
                "definition": "Mathematical modeling and quantitative optimization for executive decision-making.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "52.1302",
                "title": "Business Statistics",
                "definition": "Time series forecasting, multivariate predictive regression, and customer retention analysis.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.1304",
                "title": "Actuarial Science",
                "definition": "Mortality tables, life insurance risk modeling, loss reserves, and risk pricing theory.",
                "stem_designated": True,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.1401",
                "title": "Marketing/Marketing Management, General",
                "definition": "Customer discovery, product positioning, marketing mix (4Ps), and omnichannel advertising.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE'],
            },
            {
                "cip_code": "52.1402",
                "title": "Marketing Research",
                "definition": "Consumer surveys, focus groups, conjoint analysis, and brand sentiment analytics.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.1403",
                "title": "International Marketing",
                "definition": "Global market entry strategy, cultural localization, export controls, and foreign distribution.",
                "stem_designated": False,
                "degree_levels": ['BACHELOR', 'MASTER'],
            },
            {
                "cip_code": "52.1701",
                "title": "Insurance",
                "definition": "Underwriting risk analysis, property/casualty policies, reinsurance pools, and claims handling.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
            {
                "cip_code": "52.1801",
                "title": "Sales, Distribution, and Marketing Operations",
                "definition": "B2B sales pipeline management, quota structures, negotiations, and distributor contracts.",
                "stem_designated": False,
                "degree_levels": ['ASSOCIATE', 'BACHELOR'],
            },
        ]
    },
]

ALL_CIP_PROGRAMS = [p for s in CIP_SERIES_CATALOG for p in s["programs"]]
CIP_BY_CODE = {p["cip_code"]: p for p in ALL_CIP_PROGRAMS}
