"""
ISO 3166-1 Country Profiles & Global Higher Education Accreditation Authorities
"""

COUNTRIES = [
    {
        "iso2": "AF",
        "iso3": "AFG",
        "numeric": "004",
        "name": "Afghanistan",
        "capital": "Kabul",
        "currency": "AFN",
        "phone_code": "+93",
        "accreditation_authority": "Ministry of Higher Education (MoHE)",
    },
    {
        "iso2": "AL",
        "iso3": "ALB",
        "numeric": "008",
        "name": "Albania",
        "capital": "Tirana",
        "currency": "ALL",
        "phone_code": "+355",
        "accreditation_authority": "Quality Assurance Agency in Higher Education (ASCAL)",
    },
    {
        "iso2": "DZ",
        "iso3": "DZA",
        "numeric": "012",
        "name": "Algeria",
        "capital": "Algiers",
        "currency": "DZD",
        "phone_code": "+213",
        "accreditation_authority": "Ministry of Higher Education and Scientific Research (MESRS)",
    },
    {
        "iso2": "AD",
        "iso3": "AND",
        "numeric": "020",
        "name": "Andorra",
        "capital": "Andorra la Vella",
        "currency": "EUR",
        "phone_code": "+376",
        "accreditation_authority": "Agència de Qualitat de l'Ensenyament Superior d'Andorra (AQUA)",
    },
    {
        "iso2": "AO",
        "iso3": "AGO",
        "numeric": "024",
        "name": "Angola",
        "capital": "Luanda",
        "currency": "AOA",
        "phone_code": "+244",
        "accreditation_authority": "Ministry of Higher Education, Science, Technology and Innovation (MESCTI)",
    },
    {
        "iso2": "AG",
        "iso3": "ATG",
        "numeric": "028",
        "name": "Antigua and Barbuda",
        "capital": "St. John's",
        "currency": "XCD",
        "phone_code": "+1-268",
        "accreditation_authority": "Antigua and Barbuda National Accreditation Board (ABNAB)",
    },
    {
        "iso2": "AR",
        "iso3": "ARG",
        "numeric": "032",
        "name": "Argentina",
        "capital": "Buenos Aires",
        "currency": "ARS",
        "phone_code": "+54",
        "accreditation_authority": "Comisión Nacional de Evaluación y Acreditación Universitaria (CONEAU)",
    },
    {
        "iso2": "AM",
        "iso3": "ARM",
        "numeric": "051",
        "name": "Armenia",
        "capital": "Yerevan",
        "currency": "AMD",
        "phone_code": "+374",
        "accreditation_authority": "National Center for Professional Education Quality Assurance (ANQA)",
    },
    {
        "iso2": "AU",
        "iso3": "AUS",
        "numeric": "036",
        "name": "Australia",
        "capital": "Canberra",
        "currency": "AUD",
        "phone_code": "+61",
        "accreditation_authority": "Tertiary Education Quality and Standards Agency (TEQSA)",
    },
    {
        "iso2": "AT",
        "iso3": "AUT",
        "numeric": "040",
        "name": "Austria",
        "capital": "Vienna",
        "currency": "EUR",
        "phone_code": "+43",
        "accreditation_authority": "Agency for Quality Assurance and Accreditation Austria (AQ Austria)",
    },
    {
        "iso2": "AZ",
        "iso3": "AZE",
        "numeric": "031",
        "name": "Azerbaijan",
        "capital": "Baku",
        "currency": "AZN",
        "phone_code": "+994",
        "accreditation_authority": "Quality Assurance Agency in Education (TKTA)",
    },
    {
        "iso2": "BS",
        "iso3": "BHS",
        "numeric": "044",
        "name": "Bahamas",
        "capital": "Nassau",
        "currency": "BSD",
        "phone_code": "+1-242",
        "accreditation_authority": "National Accreditation and Equivalency Council of The Bahamas (NAECOB)",
    },
    {
        "iso2": "BH",
        "iso3": "BHR",
        "numeric": "048",
        "name": "Bahrain",
        "capital": "Manama",
        "currency": "BHD",
        "phone_code": "+973",
        "accreditation_authority": "Education and Training Quality Authority (BQA)",
    },
    {
        "iso2": "BD",
        "iso3": "BGD",
        "numeric": "050",
        "name": "Bangladesh",
        "capital": "Dhaka",
        "currency": "BDT",
        "phone_code": "+880",
        "accreditation_authority": "Bangladesh Accreditation Council (BAC) / University Grants Commission (UGC)",
    },
    {
        "iso2": "BB",
        "iso3": "BRB",
        "numeric": "052",
        "name": "Barbados",
        "capital": "Bridgetown",
        "currency": "BBD",
        "phone_code": "+1-246",
        "accreditation_authority": "Barbados Accreditation Council (BAC)",
    },
    {
        "iso2": "BY",
        "iso3": "BLR",
        "numeric": "112",
        "name": "Belarus",
        "capital": "Minsk",
        "currency": "BYN",
        "phone_code": "+375",
        "accreditation_authority": "Department of Quality Control of Education, Ministry of Education",
    },
    {
        "iso2": "BE",
        "iso3": "BEL",
        "numeric": "056",
        "name": "Belgium",
        "capital": "Brussels",
        "currency": "EUR",
        "phone_code": "+32",
        "accreditation_authority": "Accreditation Organisation of the Netherlands and Flanders (NVAO)",
    },
    {
        "iso2": "BZ",
        "iso3": "BLZ",
        "numeric": "084",
        "name": "Belize",
        "capital": "Belmopan",
        "currency": "BZD",
        "phone_code": "+501",
        "accreditation_authority": "Association of Tertiary Level Institutions of Belize (ATLIB)",
    },
    {
        "iso2": "BJ",
        "iso3": "BEN",
        "numeric": "204",
        "name": "Benin",
        "capital": "Porto-Novo",
        "currency": "XOF",
        "phone_code": "+229",
        "accreditation_authority": "National Directorate of Higher Education (DGES)",
    },
    {
        "iso2": "BT",
        "iso3": "BTN",
        "numeric": "064",
        "name": "Bhutan",
        "capital": "Thimphu",
        "currency": "BTN",
        "phone_code": "+975",
        "accreditation_authority": "Bhutan Qualifications and Professionals Certification Authority (BQPCA)",
    },
    {
        "iso2": "BO",
        "iso3": "BOL",
        "numeric": "068",
        "name": "Bolivia",
        "capital": "Sucre",
        "currency": "BOB",
        "phone_code": "+591",
        "accreditation_authority": "Ministry of Education - Vice Ministry of Higher Education",
    },
    {
        "iso2": "BA",
        "iso3": "BIH",
        "numeric": "070",
        "name": "Bosnia and Herzegovina",
        "capital": "Sarajevo",
        "currency": "BAM",
        "phone_code": "+387",
        "accreditation_authority": "Agency for Development of Higher Education and Quality Assurance (HEA)",
    },
    {
        "iso2": "BW",
        "iso3": "BWA",
        "numeric": "072",
        "name": "Botswana",
        "capital": "Gaborone",
        "currency": "BWP",
        "phone_code": "+267",
        "accreditation_authority": "Botswana Qualifications Authority (BQA)",
    },
    {
        "iso2": "BR",
        "iso3": "BRA",
        "numeric": "076",
        "name": "Brazil",
        "capital": "Brasília",
        "currency": "BRL",
        "phone_code": "+55",
        "accreditation_authority": "National Institute for Educational Studies and Research (INEP / CAPES)",
    },
    {
        "iso2": "BN",
        "iso3": "BRN",
        "numeric": "096",
        "name": "Brunei",
        "capital": "Bandar Seri Begawan",
        "currency": "BND",
        "phone_code": "+673",
        "accreditation_authority": "Brunei Darussalam National Accreditation Council (BDNAC)",
    },
    {
        "iso2": "BG",
        "iso3": "BGR",
        "numeric": "100",
        "name": "Bulgaria",
        "capital": "Sofia",
        "currency": "BGN",
        "phone_code": "+359",
        "accreditation_authority": "National Evaluation and Accreditation Agency (NEAA)",
    },
    {
        "iso2": "BF",
        "iso3": "BFA",
        "numeric": "854",
        "name": "Burkina Faso",
        "capital": "Ouagadougou",
        "currency": "XOF",
        "phone_code": "+226",
        "accreditation_authority": "African and Malagasy Council for Higher Education (CAMES)",
    },
    {
        "iso2": "BI",
        "iso3": "BDI",
        "numeric": "108",
        "name": "Burundi",
        "capital": "Gitega",
        "currency": "BIF",
        "phone_code": "+257",
        "accreditation_authority": "National Commission for Higher Education (CNES)",
    },
    {
        "iso2": "KH",
        "iso3": "KHM",
        "numeric": "116",
        "name": "Cambodia",
        "capital": "Phnom Penh",
        "currency": "KHR",
        "phone_code": "+855",
        "accreditation_authority": "Accreditation Committee of Cambodia (ACC)",
    },
    {
        "iso2": "CM",
        "iso3": "CMR",
        "numeric": "120",
        "name": "Cameroon",
        "capital": "Yaoundé",
        "currency": "XAF",
        "phone_code": "+237",
        "accreditation_authority": "Ministry of Higher Education (MINESUP)",
    },
    {
        "iso2": "CA",
        "iso3": "CAN",
        "numeric": "124",
        "name": "Canada",
        "capital": "Ottawa",
        "currency": "CAD",
        "phone_code": "+1",
        "accreditation_authority": "Canadian Degree Granting Authorities & Provincial Quality Councils (PEQAB, OUCQA)",
    },
    {
        "iso2": "CL",
        "iso3": "CHL",
        "numeric": "152",
        "name": "Chile",
        "capital": "Santiago",
        "currency": "CLP",
        "phone_code": "+56",
        "accreditation_authority": "Comisión Nacional de Acreditación (CNA-Chile)",
    },
    {
        "iso2": "CN",
        "iso3": "CHN",
        "numeric": "156",
        "name": "China",
        "capital": "Beijing",
        "currency": "CNY",
        "phone_code": "+86",
        "accreditation_authority": "Higher Education Evaluation Center of the Ministry of Education (HEEC)",
    },
    {
        "iso2": "CO",
        "iso3": "COL",
        "numeric": "170",
        "name": "Colombia",
        "capital": "Bogotá",
        "currency": "COP",
        "phone_code": "+57",
        "accreditation_authority": "Consejo Nacional de Acreditación (CNA)",
    },
    {
        "iso2": "CR",
        "iso3": "CRI",
        "numeric": "188",
        "name": "Costa Rica",
        "capital": "San José",
        "currency": "CRC",
        "phone_code": "+506",
        "accreditation_authority": "Sistema Nacional de Acreditación de la Educación Superior (SINAES)",
    },
    {
        "iso2": "HR",
        "iso3": "HRV",
        "numeric": "191",
        "name": "Croatia",
        "capital": "Zagreb",
        "currency": "EUR",
        "phone_code": "+385",
        "accreditation_authority": "Agency for Science and Higher Education (ASHE / AZVO)",
    },
    {
        "iso2": "CY",
        "iso3": "CYP",
        "numeric": "196",
        "name": "Cyprus",
        "capital": "Nicosia",
        "currency": "EUR",
        "phone_code": "+357",
        "accreditation_authority": "Cyprus Agency of Quality Assurance and Accreditation in Higher Education (CYQAA)",
    },
    {
        "iso2": "CZ",
        "iso3": "CZE",
        "numeric": "203",
        "name": "Czech Republic",
        "capital": "Prague",
        "currency": "CZK",
        "phone_code": "+420",
        "accreditation_authority": "National Accreditation Bureau for Higher Education (NAB / NAÚ)",
    },
    {
        "iso2": "DK",
        "iso3": "DNK",
        "numeric": "208",
        "name": "Denmark",
        "capital": "Copenhagen",
        "currency": "DKK",
        "phone_code": "+45",
        "accreditation_authority": "Danish Accreditation Institution (Danmarks Akkrediteringsinstitution)",
    },
    {
        "iso2": "DO",
        "iso3": "DOM",
        "numeric": "214",
        "name": "Dominican Republic",
        "capital": "Santo Domingo",
        "currency": "DOP",
        "phone_code": "+1-809",
        "accreditation_authority": "Ministry of Higher Education, Science and Technology (MESCYT)",
    },
    {
        "iso2": "EC",
        "iso3": "ECU",
        "numeric": "218",
        "name": "Ecuador",
        "capital": "Quito",
        "currency": "USD",
        "phone_code": "+593",
        "accreditation_authority": "Consejo de Aseguramiento de la Calidad de la Educación Superior (CACES)",
    },
    {
        "iso2": "EG",
        "iso3": "EGY",
        "numeric": "818",
        "name": "Egypt",
        "capital": "Cairo",
        "currency": "EGP",
        "phone_code": "+20",
        "accreditation_authority": "National Authority for Quality Assurance and Accreditation of Education (NAQAAE)",
    },
    {
        "iso2": "EE",
        "iso3": "EST",
        "numeric": "233",
        "name": "Estonia",
        "capital": "Tallinn",
        "currency": "EUR",
        "phone_code": "+372",
        "accreditation_authority": "Estonian Quality Agency for Education (HAKA)",
    },
    {
        "iso2": "ET",
        "iso3": "ETH",
        "numeric": "231",
        "name": "Ethiopia",
        "capital": "Addis Ababa",
        "currency": "ETB",
        "phone_code": "+251",
        "accreditation_authority": "Education and Training Authority (ETA)",
    },
    {
        "iso2": "FI",
        "iso3": "FIN",
        "numeric": "246",
        "name": "Finland",
        "capital": "Helsinki",
        "currency": "EUR",
        "phone_code": "+358",
        "accreditation_authority": "Finnish Education Evaluation Centre (FINEEC)",
    },
    {
        "iso2": "FR",
        "iso3": "FRA",
        "numeric": "250",
        "name": "France",
        "capital": "Paris",
        "currency": "EUR",
        "phone_code": "+33",
        "accreditation_authority": "High Council for the Evaluation of Research and Higher Education (Hcéres / CTI)",
    },
    {
        "iso2": "GE",
        "iso3": "GEO",
        "numeric": "268",
        "name": "Georgia",
        "capital": "Tbilisi",
        "currency": "GEL",
        "phone_code": "+995",
        "accreditation_authority": "National Center for Educational Quality Enhancement (NCEQE)",
    },
    {
        "iso2": "DE",
        "iso3": "DEU",
        "numeric": "276",
        "name": "Germany",
        "capital": "Berlin",
        "currency": "EUR",
        "phone_code": "+49",
        "accreditation_authority": "German Accreditation Council (Akkreditierungsrat / ASIIN / ZEvA)",
    },
    {
        "iso2": "GH",
        "iso3": "GHA",
        "numeric": "288",
        "name": "Ghana",
        "capital": "Accra",
        "currency": "GHS",
        "phone_code": "+233",
        "accreditation_authority": "Ghana Tertiary Education Commission (GTEC)",
    },
    {
        "iso2": "GR",
        "iso3": "GRC",
        "numeric": "300",
        "name": "Greece",
        "capital": "Athens",
        "currency": "EUR",
        "phone_code": "+30",
        "accreditation_authority": "Hellenic Authority for Higher Education (HAHE)",
    },
    {
        "iso2": "HU",
        "iso3": "HUN",
        "numeric": "348",
        "name": "Hungary",
        "capital": "Budapest",
        "currency": "HUF",
        "phone_code": "+36",
        "accreditation_authority": "Hungarian Accreditation Committee (MAB)",
    },
    {
        "iso2": "IS",
        "iso3": "ISL",
        "numeric": "352",
        "name": "Iceland",
        "capital": "Reykjavík",
        "currency": "ISK",
        "phone_code": "+354",
        "accreditation_authority": "Quality Board for Icelandic Higher Education",
    },
    {
        "iso2": "IN",
        "iso3": "IND",
        "numeric": "356",
        "name": "India",
        "capital": "New Delhi",
        "currency": "INR",
        "phone_code": "+91",
        "accreditation_authority": "National Assessment and Accreditation Council (NAAC) / National Board of Accreditation (NBA)",
    },
    {
        "iso2": "ID",
        "iso3": "IDN",
        "numeric": "360",
        "name": "Indonesia",
        "capital": "Jakarta",
        "currency": "IDR",
        "phone_code": "+62",
        "accreditation_authority": "National Accreditation Agency for Higher Education (BAN-PT) / LAM-INFOKOM",
    },
    {
        "iso2": "IE",
        "iso3": "IRL",
        "numeric": "372",
        "name": "Ireland",
        "capital": "Dublin",
        "currency": "EUR",
        "phone_code": "+353",
        "accreditation_authority": "Quality and Qualifications Ireland (QQI)",
    },
    {
        "iso2": "IL",
        "iso3": "ISR",
        "numeric": "376",
        "name": "Israel",
        "capital": "Jerusalem",
        "currency": "ILS",
        "phone_code": "+972",
        "accreditation_authority": "Council for Higher Education (CHE / MALAG)",
    },
    {
        "iso2": "IT",
        "iso3": "ITA",
        "numeric": "380",
        "name": "Italy",
        "capital": "Rome",
        "currency": "EUR",
        "phone_code": "+39",
        "accreditation_authority": "National Agency for the Evaluation of Universities and Research Institutes (ANVUR)",
    },
    {
        "iso2": "JP",
        "iso3": "JPN",
        "numeric": "392",
        "name": "Japan",
        "capital": "Tokyo",
        "currency": "JPY",
        "phone_code": "+81",
        "accreditation_authority": "Japan University Accreditation Association (JUAA) / NIAD-QE",
    },
    {
        "iso2": "JO",
        "iso3": "JOR",
        "numeric": "400",
        "name": "Jordan",
        "capital": "Amman",
        "currency": "JOD",
        "phone_code": "+962",
        "accreditation_authority": "Accreditation and Quality Assurance Commission for Higher Education Institutions (AQACHEI)",
    },
    {
        "iso2": "KZ",
        "iso3": "KAZ",
        "numeric": "398",
        "name": "Kazakhstan",
        "capital": "Astana",
        "currency": "KZT",
        "phone_code": "+7",
        "accreditation_authority": "Independent Agency for Accreditation and Rating (IAAR / IQAA)",
    },
    {
        "iso2": "KE",
        "iso3": "KEN",
        "numeric": "404",
        "name": "Kenya",
        "capital": "Nairobi",
        "currency": "KES",
        "phone_code": "+254",
        "accreditation_authority": "Commission for University Education (CUE)",
    },
    {
        "iso2": "KR",
        "iso3": "KOR",
        "numeric": "410",
        "name": "South Korea",
        "capital": "Seoul",
        "currency": "KRW",
        "phone_code": "+82",
        "accreditation_authority": "Korean Council for University Education (KCUE) / ABEEK",
    },
    {
        "iso2": "KW",
        "iso3": "KWT",
        "numeric": "414",
        "name": "Kuwait",
        "capital": "Kuwait City",
        "currency": "KWD",
        "phone_code": "+965",
        "accreditation_authority": "National Bureau for Academic Accreditation and Education Quality Assurance (NBAQ)",
    },
    {
        "iso2": "LV",
        "iso3": "LVA",
        "numeric": "428",
        "name": "Latvia",
        "capital": "Riga",
        "currency": "EUR",
        "phone_code": "+371",
        "accreditation_authority": "Academic Information Centre - Quality Agency for Higher Education (AIKA)",
    },
    {
        "iso2": "LB",
        "iso3": "LBN",
        "numeric": "422",
        "name": "Lebanon",
        "capital": "Beirut",
        "currency": "LBP",
        "phone_code": "+961",
        "accreditation_authority": "General Directorate of Higher Education (GDHE)",
    },
    {
        "iso2": "LT",
        "iso3": "LTU",
        "numeric": "440",
        "name": "Lithuania",
        "capital": "Vilnius",
        "currency": "EUR",
        "phone_code": "+370",
        "accreditation_authority": "Centre for Quality Assessment in Higher Education (SKVC)",
    },
    {
        "iso2": "LU",
        "iso3": "LUX",
        "numeric": "442",
        "name": "Luxembourg",
        "capital": "Luxembourg",
        "currency": "EUR",
        "phone_code": "+352",
        "accreditation_authority": "Ministry of Higher Education and Research",
    },
    {
        "iso2": "MY",
        "iso3": "MYS",
        "numeric": "458",
        "name": "Malaysia",
        "capital": "Kuala Lumpur",
        "currency": "MYR",
        "phone_code": "+60",
        "accreditation_authority": "Malaysian Qualifications Agency (MQA)",
    },
    {
        "iso2": "MX",
        "iso3": "MEX",
        "numeric": "484",
        "name": "Mexico",
        "capital": "Mexico City",
        "currency": "MXN",
        "phone_code": "+52",
        "accreditation_authority": "Consejo para la Acreditación de la Educación Superior (COPAES) / CENEVAL",
    },
    {
        "iso2": "NL",
        "iso3": "NLD",
        "numeric": "528",
        "name": "Netherlands",
        "capital": "Amsterdam",
        "currency": "EUR",
        "phone_code": "+31",
        "accreditation_authority": "Accreditation Organisation of the Netherlands and Flanders (NVAO)",
    },
    {
        "iso2": "NZ",
        "iso3": "NZL",
        "numeric": "554",
        "name": "New Zealand",
        "capital": "Wellington",
        "currency": "NZD",
        "phone_code": "+64",
        "accreditation_authority": "New Zealand Qualifications Authority (NZQA) / Academic Quality Agency (AQA)",
    },
    {
        "iso2": "NG",
        "iso3": "NGA",
        "numeric": "566",
        "name": "Nigeria",
        "capital": "Abuja",
        "currency": "NGN",
        "phone_code": "+234",
        "accreditation_authority": "National Universities Commission (NUC)",
    },
    {
        "iso2": "NO",
        "iso3": "NOR",
        "numeric": "578",
        "name": "Norway",
        "capital": "Oslo",
        "currency": "NOK",
        "phone_code": "+47",
        "accreditation_authority": "Norwegian Agency for Quality Assurance in Education (NOKUT)",
    },
    {
        "iso2": "PK",
        "iso3": "PAK",
        "numeric": "586",
        "name": "Pakistan",
        "capital": "Islamabad",
        "currency": "PKR",
        "phone_code": "+92",
        "accreditation_authority": "Higher Education Commission (HEC) / National Computing Education Accreditation Council (NCEAC)",
    },
    {
        "iso2": "PH",
        "iso3": "PHL",
        "numeric": "608",
        "name": "Philippines",
        "capital": "Manila",
        "currency": "PHP",
        "phone_code": "+63",
        "accreditation_authority": "Commission on Higher Education (CHED) / PAASCU",
    },
    {
        "iso2": "PL",
        "iso3": "POL",
        "numeric": "616",
        "name": "Poland",
        "capital": "Warsaw",
        "currency": "PLN",
        "phone_code": "+48",
        "accreditation_authority": "Polish Accreditation Committee (PKA)",
    },
    {
        "iso2": "PT",
        "iso3": "PRT",
        "numeric": "620",
        "name": "Portugal",
        "capital": "Lisbon",
        "currency": "EUR",
        "phone_code": "+351",
        "accreditation_authority": "Agency for Assessment and Accreditation of Higher Education (A3ES)",
    },
    {
        "iso2": "QA",
        "iso3": "QAT",
        "numeric": "634",
        "name": "Qatar",
        "capital": "Doha",
        "currency": "QAR",
        "phone_code": "+974",
        "accreditation_authority": "Ministry of Education and Higher Education - Higher Education Institute",
    },
    {
        "iso2": "RO",
        "iso3": "ROU",
        "numeric": "642",
        "name": "Romania",
        "capital": "Bucharest",
        "currency": "RON",
        "phone_code": "+40",
        "accreditation_authority": "Romanian Agency for Quality Assurance in Higher Education (ARACIS)",
    },
    {
        "iso2": "SA",
        "iso3": "SAU",
        "numeric": "682",
        "name": "Saudi Arabia",
        "capital": "Riyadh",
        "currency": "SAR",
        "phone_code": "+966",
        "accreditation_authority": "Education and Training Evaluation Commission (ETEC / NCAAA)",
    },
    {
        "iso2": "SG",
        "iso3": "SGP",
        "numeric": "702",
        "name": "Singapore",
        "capital": "Singapore",
        "currency": "SGD",
        "phone_code": "+65",
        "accreditation_authority": "Ministry of Education - Higher Education Division / SkillsFuture Singapore",
    },
    {
        "iso2": "ZA",
        "iso3": "ZAF",
        "numeric": "710",
        "name": "South Africa",
        "capital": "Pretoria",
        "currency": "ZAR",
        "phone_code": "+27",
        "accreditation_authority": "Council on Higher Education (CHE) / Higher Education Quality Committee (HEQC)",
    },
    {
        "iso2": "ES",
        "iso3": "ESP",
        "numeric": "724",
        "name": "Spain",
        "capital": "Madrid",
        "currency": "EUR",
        "phone_code": "+34",
        "accreditation_authority": "National Agency for Quality Assessment and Accreditation of Spain (ANECA)",
    },
    {
        "iso2": "SE",
        "iso3": "SWE",
        "numeric": "752",
        "name": "Sweden",
        "capital": "Stockholm",
        "currency": "SEK",
        "phone_code": "+46",
        "accreditation_authority": "Swedish Higher Education Authority (UKÄ)",
    },
    {
        "iso2": "CH",
        "iso3": "CHE",
        "numeric": "756",
        "name": "Switzerland",
        "capital": "Bern",
        "currency": "CHF",
        "phone_code": "+41",
        "accreditation_authority": "Swiss Accreditation Council (Schweizerischer Akkreditierungsrat / AAQ)",
    },
    {
        "iso2": "TW",
        "iso3": "TWN",
        "numeric": "158",
        "name": "Taiwan",
        "capital": "Taipei",
        "currency": "TWD",
        "phone_code": "+886",
        "accreditation_authority": "Higher Education Evaluation and Accreditation Council of Taiwan (HEEACT) / IEET",
    },
    {
        "iso2": "TH",
        "iso3": "THA",
        "numeric": "764",
        "name": "Thailand",
        "capital": "Bangkok",
        "currency": "THB",
        "phone_code": "+66",
        "accreditation_authority": "Office of the Higher Education Commission (OHEC) / ONESQA",
    },
    {
        "iso2": "TR",
        "iso3": "TUR",
        "numeric": "792",
        "name": "Turkey",
        "capital": "Ankara",
        "currency": "TRY",
        "phone_code": "+90",
        "accreditation_authority": "Higher Education Quality Council of Turkey (THEQC / YÖKAK)",
    },
    {
        "iso2": "UA",
        "iso3": "UKR",
        "numeric": "804",
        "name": "Ukraine",
        "capital": "Kyiv",
        "currency": "UAH",
        "phone_code": "+380",
        "accreditation_authority": "National Agency for Higher Education Quality Assurance (NAQA)",
    },
    {
        "iso2": "AE",
        "iso3": "ARE",
        "numeric": "784",
        "name": "United Arab Emirates",
        "capital": "Abu Dhabi",
        "currency": "AED",
        "phone_code": "+971",
        "accreditation_authority": "Commission for Academic Accreditation (CAA)",
    },
    {
        "iso2": "GB",
        "iso3": "GBR",
        "numeric": "826",
        "name": "United Kingdom",
        "capital": "London",
        "currency": "GBP",
        "phone_code": "+44",
        "accreditation_authority": "Quality Assurance Agency for Higher Education (QAA) / Office for Students (OfS)",
    },
    {
        "iso2": "US",
        "iso3": "USA",
        "numeric": "840",
        "name": "United States",
        "capital": "Washington, D.C.",
        "currency": "USD",
        "phone_code": "+1",
        "accreditation_authority": "Council for Higher Education Accreditation (CHEA) / Regional Commissions (NECHE, SACSCOC, HLC, MSCHE, WSCUC, NWCCU)",
    },
    {
        "iso2": "VN",
        "iso3": "VNM",
        "numeric": "704",
        "name": "Vietnam",
        "capital": "Hanoi",
        "currency": "VND",
        "phone_code": "+84",
        "accreditation_authority": "Vietnam Education Quality Agency (VEQA) / Ministry of Education and Training (MOET)",
    },
]

COUNTRIES_BY_ISO2 = {c["iso2"]: c for c in COUNTRIES}
COUNTRIES_BY_ISO3 = {c["iso3"]: c for c in COUNTRIES}
