# Generated by Django 5.0.6 on 2026-09-17 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('courses', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('instructions_html', models.TextField()),
                ('total_points', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('submission_type', models.CharField(choices=[('FILE_UPLOAD', 'File Attachment Upload (PDF, ZIP, DOCX)'), ('TEXT_ENTRY', 'Rich Text Form Submission'), ('URL_LINK', 'Live URL / Git Repository Link'), ('CODE_ARCHIVE', 'Source Code Archive with Manifest')], default='FILE_UPLOAD', max_length=30)),
                ('allowed_extensions', models.CharField(default='pdf,zip,docx,py,ipynb', max_length=200)),
                ('max_file_size_mb', models.PositiveIntegerField(default=25)),
                ('due_date', models.DateTimeField()),
                ('late_deadline', models.DateTimeField(blank=True, null=True)),
                ('late_penalty_per_day', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('peer_review_enabled', models.BooleanField(default=False)),
                ('peer_reviews_required', models.PositiveIntegerField(default=2)),
                ('is_published', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.campus', verbose_name='Campus Location')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.academicdepartment', verbose_name='Academic Department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='institutions.institution', verbose_name='Institution / Organization')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentrubric')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('submission_number', models.PositiveIntegerField(default=1)),
                ('text_content', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_days', models.PositiveIntegerField(default=0)),
                ('raw_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('late_penalty_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('final_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted on Time'), ('LATE_SUBMITTED', 'Submitted Late'), ('UNDER_REVIEW', 'Under Faculty / TA Review'), ('GRADED', 'Graded & Feedback Available'), ('RESUBMIT_REQUESTED', 'Revision Requested')], default='SUBMITTED', max_length=30)),
                ('faculty_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'student', 'submission_number')},
            },
        ),
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('similarity_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('matched_sources', models.JSONField(blank=True, default=list)),
                ('report_summary', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='assignments.assignmentsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.assignmentsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeerReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Peer Review'), ('COMPLETED', 'Review Completed'), ('EXPIRED', 'Review Window Expired')], default='PENDING', max_length=20)),
                ('score_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback_strengths', models.TextField(blank=True)),
                ('feedback_improvements', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='assignments.assignment')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_peer_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='assignments.assignmentsubmission')),
            ],
            options={
                'unique_together': {('reviewer', 'submission')},
            },
        ),
    ]
