# Generated by Django 5.0.6 on 2026-09-17 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('start_window', models.DateTimeField()),
                ('end_window', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'Active & In Progress'), ('COMPLETED', 'Session Concluded'), ('CANCELLED', 'Session Cancelled')], default='SCHEDULED', max_length=20)),
                ('requires_webcam', models.BooleanField(default=True)),
                ('requires_screen_share', models.BooleanField(default=False)),
                ('max_tab_switches', models.PositiveIntegerField(default=3)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='assessments.assessment')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='enrollments.batch')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.campus', verbose_name='Campus Location')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='institutions.academicdepartment', verbose_name='Academic Department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='institutions.institution', verbose_name='Institution / Organization')),
                ('proctors', models.ManyToManyField(blank=True, related_name='proctored_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('STARTED', 'Attempt Initialized'), ('IN_PROGRESS', 'Taking Exam'), ('SUBMITTED', 'Submitted by Student'), ('AUTO_SUBMITTED', 'Auto-Submitted upon Time Expiry'), ('DISQUALIFIED', 'Disqualified by Proctor / Anti-Cheat'), ('GRADED', 'Grading Finalized')], default='STARTED', max_length=30)),
                ('score_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('percentage_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_passed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='examinations.examsession')),
            ],
            options={
                'unique_together': {('session', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('event_type', models.CharField(choices=[('TAB_SWITCH', 'Focus Lost / Switched Browser Tab'), ('FULLSCREEN_EXIT', 'Exited Fullscreen Mode'), ('FACE_LOST', 'Webcam: No Face Detected'), ('MULTIPLE_FACES', 'Webcam: Multiple Faces Detected'), ('SUSPICIOUS_AUDIO', 'Audio Threshold Exceeded'), ('COPY_PASTE_ATTEMPT', 'Clipboard Copy/Paste Attempted'), ('DEVTOOLS_OPENED', 'Browser Developer Tools Detected'), ('IP_ANOMALY', 'IP Address Changed Mid-Session')], max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low Advisory'), ('MEDIUM', 'Moderate Warning'), ('HIGH', 'Severe Incident'), ('CRITICAL', 'Automatic Disqualification Trigger')], default='MEDIUM', max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('payload_data', models.JSONField(blank=True, default=dict)),
                ('snapshot_url', models.URLField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='examinations.examattempt')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('extra_time_minutes', models.PositiveIntegerField(default=30)),
                ('separate_testing_room', models.BooleanField(default=False)),
                ('special_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accommodations', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_accommodations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('selected_options_json', models.JSONField(blank=True, default=list)),
                ('text_response', models.TextField(blank=True)),
                ('code_response', models.TextField(blank=True)),
                ('points_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_correct', models.BooleanField(default=False)),
                ('evaluator_feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='examinations.examattempt')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.questionoption')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
